resilience4j:
  bulkhead:
    instances:
      miServicio:
        max-concurrent-calls: 3
        max-wait-duration: 1s
  
  timelimiter:
    instances:
      miServicio:
        timeout-duration: 4s
  
  retry:
    instances:
      miServicio:
        max-attempts: 3
        wait-duration: 1s

server:
  port: 8080