server:
  port: 8080

resilience4j:
  bulkhead:
    instances:
      miServicio:
        max-concurrent-calls: 3
        max-wait-duration: 0
  
  retry:
    instances:
      miServicio:
        max-attempts: 3
        wait-duration: 1s